/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha

import (
	"context"
	time "time"

	versioned "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/clientset/versioned"
	internalinterfaces "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/informers/externalversions/internalinterfaces"
	v1alpha "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/listers/example/v1alpha"
	examplev1alpha "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MydeviceAllocationStateInformer provides access to a shared informer and lister for
// MydeviceAllocationStates.
type MydeviceAllocationStateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha.MydeviceAllocationStateLister
}

type mydeviceAllocationStateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMydeviceAllocationStateInformer constructs a new informer for MydeviceAllocationState type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMydeviceAllocationStateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMydeviceAllocationStateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMydeviceAllocationStateInformer constructs a new informer for MydeviceAllocationState type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMydeviceAllocationStateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DraV1alpha().MydeviceAllocationStates(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DraV1alpha().MydeviceAllocationStates(namespace).Watch(context.TODO(), options)
			},
		},
		&examplev1alpha.MydeviceAllocationState{},
		resyncPeriod,
		indexers,
	)
}

func (f *mydeviceAllocationStateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMydeviceAllocationStateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mydeviceAllocationStateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&examplev1alpha.MydeviceAllocationState{}, f.defaultInformer)
}

func (f *mydeviceAllocationStateInformer) Lister() v1alpha.MydeviceAllocationStateLister {
	return v1alpha.NewMydeviceAllocationStateLister(f.Informer().GetIndexer())
}
