/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha

import (
	"context"
	time "time"

	versioned "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/clientset/versioned"
	internalinterfaces "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/informers/externalversions/internalinterfaces"
	v1alpha "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/listers/example/v1alpha"
	examplev1alpha "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MydeviceClaimParametersInformer provides access to a shared informer and lister for
// MydeviceClaimParameters.
type MydeviceClaimParametersInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha.MydeviceClaimParametersLister
}

type mydeviceClaimParametersInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMydeviceClaimParametersInformer constructs a new informer for MydeviceClaimParameters type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMydeviceClaimParametersInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMydeviceClaimParametersInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMydeviceClaimParametersInformer constructs a new informer for MydeviceClaimParameters type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMydeviceClaimParametersInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DraV1alpha().MydeviceClaimParameters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DraV1alpha().MydeviceClaimParameters(namespace).Watch(context.TODO(), options)
			},
		},
		&examplev1alpha.MydeviceClaimParameters{},
		resyncPeriod,
		indexers,
	)
}

func (f *mydeviceClaimParametersInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMydeviceClaimParametersInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mydeviceClaimParametersInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&examplev1alpha.MydeviceClaimParameters{}, f.defaultInformer)
}

func (f *mydeviceClaimParametersInformer) Lister() v1alpha.MydeviceClaimParametersLister {
	return v1alpha.NewMydeviceClaimParametersLister(f.Informer().GetIndexer())
}
