/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	"context"
	"time"

	scheme "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/clientset/versioned/scheme"
	v1alpha "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MydeviceClaimParametersGetter has a method to return a MydeviceClaimParametersInterface.
// A group's client should implement this interface.
type MydeviceClaimParametersGetter interface {
	MydeviceClaimParameters(namespace string) MydeviceClaimParametersInterface
}

// MydeviceClaimParametersInterface has methods to work with MydeviceClaimParameters resources.
type MydeviceClaimParametersInterface interface {
	Create(ctx context.Context, mydeviceClaimParameters *v1alpha.MydeviceClaimParameters, opts v1.CreateOptions) (*v1alpha.MydeviceClaimParameters, error)
	Update(ctx context.Context, mydeviceClaimParameters *v1alpha.MydeviceClaimParameters, opts v1.UpdateOptions) (*v1alpha.MydeviceClaimParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha.MydeviceClaimParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha.MydeviceClaimParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.MydeviceClaimParameters, err error)
	MydeviceClaimParametersExpansion
}

// mydeviceClaimParameters implements MydeviceClaimParametersInterface
type mydeviceClaimParameters struct {
	client rest.Interface
	ns     string
}

// newMydeviceClaimParameters returns a MydeviceClaimParameters
func newMydeviceClaimParameters(c *DraV1alphaClient, namespace string) *mydeviceClaimParameters {
	return &mydeviceClaimParameters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mydeviceClaimParameters, and returns the corresponding mydeviceClaimParameters object, and an error if there is any.
func (c *mydeviceClaimParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha.MydeviceClaimParameters, err error) {
	result = &v1alpha.MydeviceClaimParameters{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mydeviceclaimparameters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MydeviceClaimParameters that match those selectors.
func (c *mydeviceClaimParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha.MydeviceClaimParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.MydeviceClaimParametersList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mydeviceclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mydeviceClaimParameters.
func (c *mydeviceClaimParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mydeviceclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mydeviceClaimParameters and creates it.  Returns the server's representation of the mydeviceClaimParameters, and an error, if there is any.
func (c *mydeviceClaimParameters) Create(ctx context.Context, mydeviceClaimParameters *v1alpha.MydeviceClaimParameters, opts v1.CreateOptions) (result *v1alpha.MydeviceClaimParameters, err error) {
	result = &v1alpha.MydeviceClaimParameters{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mydeviceclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mydeviceClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mydeviceClaimParameters and updates it. Returns the server's representation of the mydeviceClaimParameters, and an error, if there is any.
func (c *mydeviceClaimParameters) Update(ctx context.Context, mydeviceClaimParameters *v1alpha.MydeviceClaimParameters, opts v1.UpdateOptions) (result *v1alpha.MydeviceClaimParameters, err error) {
	result = &v1alpha.MydeviceClaimParameters{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mydeviceclaimparameters").
		Name(mydeviceClaimParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mydeviceClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mydeviceClaimParameters and deletes it. Returns an error if one occurs.
func (c *mydeviceClaimParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mydeviceclaimparameters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mydeviceClaimParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mydeviceclaimparameters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mydeviceClaimParameters.
func (c *mydeviceClaimParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.MydeviceClaimParameters, err error) {
	result = &v1alpha.MydeviceClaimParameters{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mydeviceclaimparameters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
