/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	"context"
	"time"

	scheme "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/clientset/versioned/scheme"
	v1alpha "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MydeviceClassParametersGetter has a method to return a MydeviceClassParametersInterface.
// A group's client should implement this interface.
type MydeviceClassParametersGetter interface {
	MydeviceClassParameters() MydeviceClassParametersInterface
}

// MydeviceClassParametersInterface has methods to work with MydeviceClassParameters resources.
type MydeviceClassParametersInterface interface {
	Create(ctx context.Context, mydeviceClassParameters *v1alpha.MydeviceClassParameters, opts v1.CreateOptions) (*v1alpha.MydeviceClassParameters, error)
	Update(ctx context.Context, mydeviceClassParameters *v1alpha.MydeviceClassParameters, opts v1.UpdateOptions) (*v1alpha.MydeviceClassParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha.MydeviceClassParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha.MydeviceClassParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.MydeviceClassParameters, err error)
	MydeviceClassParametersExpansion
}

// mydeviceClassParameters implements MydeviceClassParametersInterface
type mydeviceClassParameters struct {
	client rest.Interface
}

// newMydeviceClassParameters returns a MydeviceClassParameters
func newMydeviceClassParameters(c *DraV1alphaClient) *mydeviceClassParameters {
	return &mydeviceClassParameters{
		client: c.RESTClient(),
	}
}

// Get takes name of the mydeviceClassParameters, and returns the corresponding mydeviceClassParameters object, and an error if there is any.
func (c *mydeviceClassParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha.MydeviceClassParameters, err error) {
	result = &v1alpha.MydeviceClassParameters{}
	err = c.client.Get().
		Resource("mydeviceclassparameters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MydeviceClassParameters that match those selectors.
func (c *mydeviceClassParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha.MydeviceClassParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.MydeviceClassParametersList{}
	err = c.client.Get().
		Resource("mydeviceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mydeviceClassParameters.
func (c *mydeviceClassParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("mydeviceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mydeviceClassParameters and creates it.  Returns the server's representation of the mydeviceClassParameters, and an error, if there is any.
func (c *mydeviceClassParameters) Create(ctx context.Context, mydeviceClassParameters *v1alpha.MydeviceClassParameters, opts v1.CreateOptions) (result *v1alpha.MydeviceClassParameters, err error) {
	result = &v1alpha.MydeviceClassParameters{}
	err = c.client.Post().
		Resource("mydeviceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mydeviceClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mydeviceClassParameters and updates it. Returns the server's representation of the mydeviceClassParameters, and an error, if there is any.
func (c *mydeviceClassParameters) Update(ctx context.Context, mydeviceClassParameters *v1alpha.MydeviceClassParameters, opts v1.UpdateOptions) (result *v1alpha.MydeviceClassParameters, err error) {
	result = &v1alpha.MydeviceClassParameters{}
	err = c.client.Put().
		Resource("mydeviceclassparameters").
		Name(mydeviceClassParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mydeviceClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mydeviceClassParameters and deletes it. Returns an error if one occurs.
func (c *mydeviceClassParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("mydeviceclassparameters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mydeviceClassParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("mydeviceclassparameters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mydeviceClassParameters.
func (c *mydeviceClassParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.MydeviceClassParameters, err error) {
	result = &v1alpha.MydeviceClassParameters{}
	err = c.client.Patch(pt).
		Resource("mydeviceclassparameters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
