/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/v1alpha"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MydeviceClassParametersLister helps list MydeviceClassParameters.
// All objects returned here must be treated as read-only.
type MydeviceClassParametersLister interface {
	// List lists all MydeviceClassParameters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha.MydeviceClassParameters, err error)
	// Get retrieves the MydeviceClassParameters from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha.MydeviceClassParameters, error)
	MydeviceClassParametersListerExpansion
}

// mydeviceClassParametersLister implements the MydeviceClassParametersLister interface.
type mydeviceClassParametersLister struct {
	indexer cache.Indexer
}

// NewMydeviceClassParametersLister returns a new MydeviceClassParametersLister.
func NewMydeviceClassParametersLister(indexer cache.Indexer) MydeviceClassParametersLister {
	return &mydeviceClassParametersLister{indexer: indexer}
}

// List lists all MydeviceClassParameters in the indexer.
func (s *mydeviceClassParametersLister) List(selector labels.Selector) (ret []*v1alpha.MydeviceClassParameters, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha.MydeviceClassParameters))
	})
	return ret, err
}

// Get retrieves the MydeviceClassParameters from the index for a given name.
func (s *mydeviceClassParametersLister) Get(name string) (*v1alpha.MydeviceClassParameters, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha.Resource("mydeviceclassparameters"), name)
	}
	return obj.(*v1alpha.MydeviceClassParameters), nil
}
