/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMydeviceAllocationStates implements MydeviceAllocationStateInterface
type FakeMydeviceAllocationStates struct {
	Fake *FakeDraV1alpha
	ns   string
}

var mydeviceallocationstatesResource = schema.GroupVersionResource{Group: "dra.example.com", Version: "v1alpha", Resource: "mydeviceallocationstates"}

var mydeviceallocationstatesKind = schema.GroupVersionKind{Group: "dra.example.com", Version: "v1alpha", Kind: "MydeviceAllocationState"}

// Get takes name of the mydeviceAllocationState, and returns the corresponding mydeviceAllocationState object, and an error if there is any.
func (c *FakeMydeviceAllocationStates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha.MydeviceAllocationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mydeviceallocationstatesResource, c.ns, name), &v1alpha.MydeviceAllocationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.MydeviceAllocationState), err
}

// List takes label and field selectors, and returns the list of MydeviceAllocationStates that match those selectors.
func (c *FakeMydeviceAllocationStates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha.MydeviceAllocationStateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mydeviceallocationstatesResource, mydeviceallocationstatesKind, c.ns, opts), &v1alpha.MydeviceAllocationStateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha.MydeviceAllocationStateList{ListMeta: obj.(*v1alpha.MydeviceAllocationStateList).ListMeta}
	for _, item := range obj.(*v1alpha.MydeviceAllocationStateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mydeviceAllocationStates.
func (c *FakeMydeviceAllocationStates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mydeviceallocationstatesResource, c.ns, opts))

}

// Create takes the representation of a mydeviceAllocationState and creates it.  Returns the server's representation of the mydeviceAllocationState, and an error, if there is any.
func (c *FakeMydeviceAllocationStates) Create(ctx context.Context, mydeviceAllocationState *v1alpha.MydeviceAllocationState, opts v1.CreateOptions) (result *v1alpha.MydeviceAllocationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mydeviceallocationstatesResource, c.ns, mydeviceAllocationState), &v1alpha.MydeviceAllocationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.MydeviceAllocationState), err
}

// Update takes the representation of a mydeviceAllocationState and updates it. Returns the server's representation of the mydeviceAllocationState, and an error, if there is any.
func (c *FakeMydeviceAllocationStates) Update(ctx context.Context, mydeviceAllocationState *v1alpha.MydeviceAllocationState, opts v1.UpdateOptions) (result *v1alpha.MydeviceAllocationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mydeviceallocationstatesResource, c.ns, mydeviceAllocationState), &v1alpha.MydeviceAllocationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.MydeviceAllocationState), err
}

// Delete takes name of the mydeviceAllocationState and deletes it. Returns an error if one occurs.
func (c *FakeMydeviceAllocationStates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(mydeviceallocationstatesResource, c.ns, name, opts), &v1alpha.MydeviceAllocationState{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMydeviceAllocationStates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mydeviceallocationstatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha.MydeviceAllocationStateList{})
	return err
}

// Patch applies the patch and returns the patched mydeviceAllocationState.
func (c *FakeMydeviceAllocationStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.MydeviceAllocationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mydeviceallocationstatesResource, c.ns, name, pt, data, subresources...), &v1alpha.MydeviceAllocationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.MydeviceAllocationState), err
}
