/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha "github.com/kubernetes-sigs/dra-example-driver/pkg/crd/example/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMydeviceClassParameters implements MydeviceClassParametersInterface
type FakeMydeviceClassParameters struct {
	Fake *FakeDraV1alpha
}

var mydeviceclassparametersResource = schema.GroupVersionResource{Group: "dra.example.com", Version: "v1alpha", Resource: "mydeviceclassparameters"}

var mydeviceclassparametersKind = schema.GroupVersionKind{Group: "dra.example.com", Version: "v1alpha", Kind: "MydeviceClassParameters"}

// Get takes name of the mydeviceClassParameters, and returns the corresponding mydeviceClassParameters object, and an error if there is any.
func (c *FakeMydeviceClassParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha.MydeviceClassParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(mydeviceclassparametersResource, name), &v1alpha.MydeviceClassParameters{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.MydeviceClassParameters), err
}

// List takes label and field selectors, and returns the list of MydeviceClassParameters that match those selectors.
func (c *FakeMydeviceClassParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha.MydeviceClassParametersList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(mydeviceclassparametersResource, mydeviceclassparametersKind, opts), &v1alpha.MydeviceClassParametersList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha.MydeviceClassParametersList{ListMeta: obj.(*v1alpha.MydeviceClassParametersList).ListMeta}
	for _, item := range obj.(*v1alpha.MydeviceClassParametersList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mydeviceClassParameters.
func (c *FakeMydeviceClassParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(mydeviceclassparametersResource, opts))
}

// Create takes the representation of a mydeviceClassParameters and creates it.  Returns the server's representation of the mydeviceClassParameters, and an error, if there is any.
func (c *FakeMydeviceClassParameters) Create(ctx context.Context, mydeviceClassParameters *v1alpha.MydeviceClassParameters, opts v1.CreateOptions) (result *v1alpha.MydeviceClassParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(mydeviceclassparametersResource, mydeviceClassParameters), &v1alpha.MydeviceClassParameters{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.MydeviceClassParameters), err
}

// Update takes the representation of a mydeviceClassParameters and updates it. Returns the server's representation of the mydeviceClassParameters, and an error, if there is any.
func (c *FakeMydeviceClassParameters) Update(ctx context.Context, mydeviceClassParameters *v1alpha.MydeviceClassParameters, opts v1.UpdateOptions) (result *v1alpha.MydeviceClassParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(mydeviceclassparametersResource, mydeviceClassParameters), &v1alpha.MydeviceClassParameters{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.MydeviceClassParameters), err
}

// Delete takes name of the mydeviceClassParameters and deletes it. Returns an error if one occurs.
func (c *FakeMydeviceClassParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(mydeviceclassparametersResource, name, opts), &v1alpha.MydeviceClassParameters{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMydeviceClassParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(mydeviceclassparametersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha.MydeviceClassParametersList{})
	return err
}

// Patch applies the patch and returns the patched mydeviceClassParameters.
func (c *FakeMydeviceClassParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.MydeviceClassParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(mydeviceclassparametersResource, name, pt, data, subresources...), &v1alpha.MydeviceClassParameters{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.MydeviceClassParameters), err
}
