//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocatableMydevice) DeepCopyInto(out *AllocatableMydevice) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocatableMydevice.
func (in *AllocatableMydevice) DeepCopy() *AllocatableMydevice {
	if in == nil {
		return nil
	}
	out := new(AllocatableMydevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocatedMydevice) DeepCopyInto(out *AllocatedMydevice) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocatedMydevice.
func (in *AllocatedMydevice) DeepCopy() *AllocatedMydevice {
	if in == nil {
		return nil
	}
	out := new(AllocatedMydevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AllocatedMydevices) DeepCopyInto(out *AllocatedMydevices) {
	{
		in := &in
		*out = make(AllocatedMydevices, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocatedMydevices.
func (in AllocatedMydevices) DeepCopy() AllocatedMydevices {
	if in == nil {
		return nil
	}
	out := new(AllocatedMydevices)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceAllocationState) DeepCopyInto(out *MydeviceAllocationState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceAllocationState.
func (in *MydeviceAllocationState) DeepCopy() *MydeviceAllocationState {
	if in == nil {
		return nil
	}
	out := new(MydeviceAllocationState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MydeviceAllocationState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceAllocationStateList) DeepCopyInto(out *MydeviceAllocationStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MydeviceAllocationState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceAllocationStateList.
func (in *MydeviceAllocationStateList) DeepCopy() *MydeviceAllocationStateList {
	if in == nil {
		return nil
	}
	out := new(MydeviceAllocationStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MydeviceAllocationStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceAllocationStateSpec) DeepCopyInto(out *MydeviceAllocationStateSpec) {
	*out = *in
	if in.AllocatableMydevices != nil {
		in, out := &in.AllocatableMydevices, &out.AllocatableMydevices
		*out = make(map[string]AllocatableMydevice, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceClaimAllocations != nil {
		in, out := &in.ResourceClaimAllocations, &out.ResourceClaimAllocations
		*out = make(map[string]AllocatedMydevices, len(*in))
		for key, val := range *in {
			var outVal []AllocatedMydevice
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(AllocatedMydevices, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.ResourceClaimRequests != nil {
		in, out := &in.ResourceClaimRequests, &out.ResourceClaimRequests
		*out = make(map[string]RequestedMydevices, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceAllocationStateSpec.
func (in *MydeviceAllocationStateSpec) DeepCopy() *MydeviceAllocationStateSpec {
	if in == nil {
		return nil
	}
	out := new(MydeviceAllocationStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceClaimParameters) DeepCopyInto(out *MydeviceClaimParameters) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceClaimParameters.
func (in *MydeviceClaimParameters) DeepCopy() *MydeviceClaimParameters {
	if in == nil {
		return nil
	}
	out := new(MydeviceClaimParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MydeviceClaimParameters) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceClaimParametersList) DeepCopyInto(out *MydeviceClaimParametersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MydeviceClaimParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceClaimParametersList.
func (in *MydeviceClaimParametersList) DeepCopy() *MydeviceClaimParametersList {
	if in == nil {
		return nil
	}
	out := new(MydeviceClaimParametersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MydeviceClaimParametersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceClaimParametersSpec) DeepCopyInto(out *MydeviceClaimParametersSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceClaimParametersSpec.
func (in *MydeviceClaimParametersSpec) DeepCopy() *MydeviceClaimParametersSpec {
	if in == nil {
		return nil
	}
	out := new(MydeviceClaimParametersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceClassParameters) DeepCopyInto(out *MydeviceClassParameters) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceClassParameters.
func (in *MydeviceClassParameters) DeepCopy() *MydeviceClassParameters {
	if in == nil {
		return nil
	}
	out := new(MydeviceClassParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MydeviceClassParameters) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceClassParametersList) DeepCopyInto(out *MydeviceClassParametersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MydeviceClassParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceClassParametersList.
func (in *MydeviceClassParametersList) DeepCopy() *MydeviceClassParametersList {
	if in == nil {
		return nil
	}
	out := new(MydeviceClassParametersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MydeviceClassParametersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceClassParametersSpec) DeepCopyInto(out *MydeviceClassParametersSpec) {
	*out = *in
	if in.MydeviceSelector != nil {
		in, out := &in.MydeviceSelector, &out.MydeviceSelector
		*out = make([]MydeviceSelector, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceClassParametersSpec.
func (in *MydeviceClassParametersSpec) DeepCopy() *MydeviceClassParametersSpec {
	if in == nil {
		return nil
	}
	out := new(MydeviceClassParametersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MydeviceSelector) DeepCopyInto(out *MydeviceSelector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MydeviceSelector.
func (in *MydeviceSelector) DeepCopy() *MydeviceSelector {
	if in == nil {
		return nil
	}
	out := new(MydeviceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestedMydevice) DeepCopyInto(out *RequestedMydevice) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestedMydevice.
func (in *RequestedMydevice) DeepCopy() *RequestedMydevice {
	if in == nil {
		return nil
	}
	out := new(RequestedMydevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestedMydevices) DeepCopyInto(out *RequestedMydevices) {
	*out = *in
	out.Spec = in.Spec
	if in.Mydevices != nil {
		in, out := &in.Mydevices, &out.Mydevices
		*out = make([]RequestedMydevice, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestedMydevices.
func (in *RequestedMydevices) DeepCopy() *RequestedMydevices {
	if in == nil {
		return nil
	}
	out := new(RequestedMydevices)
	in.DeepCopyInto(out)
	return out
}
